apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-cronjob
spec:
  schedule: "*/5 * * * *"  # This will run the job every 5 minutes
  jobTemplate:
    spec:
      template:
        metadata:
          name: pranob-001
        spec:
          containers:
            - name: nginx
              image: nginx:perl
              command: ['date']
          restartPolicy: OnFailure


###################

